// <auto-generated />
using System;
using MarketPlaceCrm.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketPlaceCrm.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "80198 Metz Wall",
                            City = "Lehnerburgh",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "Nora84@yahoo.com",
                            LastName = "Koelpin",
                            Name = "Nora",
                            PhoneNumber = "499.855.4169",
                            Role = 0,
                            ZipCode = "61592"
                        },
                        new
                        {
                            Id = 2,
                            Address = "558 Izabella Spurs",
                            City = "Ryanside",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "Brandon66@gmail.com",
                            LastName = "Walter",
                            Name = "Brandon",
                            PhoneNumber = "(323) 900-7132 x1769",
                            Role = 0,
                            ZipCode = "04604-0320"
                        },
                        new
                        {
                            Id = 3,
                            Address = "928 Jacobi Falls",
                            City = "Connellyland",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Email = "Cora.Friesen79@yahoo.com",
                            LastName = "Friesen",
                            Name = "Cora",
                            PhoneNumber = "1-208-316-7176 x925",
                            Role = 0,
                            ZipCode = "93737"
                        });
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Freight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShipperID")
                        .HasColumnType("int");

                    b.Property<string>("ShipperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ShipperID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 10248,
                            Created = new DateTime(2022, 1, 17, 0, 37, 15, 338, DateTimeKind.Unspecified).AddTicks(3492),
                            CustomerID = 1,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10249,
                            Created = new DateTime(2022, 5, 1, 7, 34, 39, 961, DateTimeKind.Unspecified).AddTicks(3990),
                            CustomerID = 1,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10250,
                            Created = new DateTime(2022, 7, 20, 0, 12, 40, 466, DateTimeKind.Unspecified).AddTicks(425),
                            CustomerID = 1,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10251,
                            Created = new DateTime(2022, 7, 26, 10, 5, 44, 741, DateTimeKind.Unspecified).AddTicks(6058),
                            CustomerID = 2,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10252,
                            Created = new DateTime(2022, 3, 12, 21, 6, 22, 253, DateTimeKind.Unspecified).AddTicks(5243),
                            CustomerID = 2,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10253,
                            Created = new DateTime(2022, 4, 1, 11, 7, 10, 120, DateTimeKind.Unspecified).AddTicks(1292),
                            CustomerID = 3,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10254,
                            Created = new DateTime(2022, 11, 22, 22, 58, 29, 177, DateTimeKind.Unspecified).AddTicks(4506),
                            CustomerID = 3,
                            Deleted = false,
                            Freight = 0m,
                            RequiredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 0m,
                            OrderID = 10248,
                            ProductID = 2,
                            Qty = 5,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            Discount = 0m,
                            OrderID = 10248,
                            ProductID = 3,
                            Qty = 4,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            Discount = 0m,
                            OrderID = 10249,
                            ProductID = 7,
                            Qty = 3,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 4,
                            Discount = 0m,
                            OrderID = 10250,
                            ProductID = 10,
                            Qty = 3,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            Discount = 0m,
                            OrderID = 10248,
                            ProductID = 6,
                            Qty = 2,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            Discount = 0m,
                            OrderID = 10248,
                            ProductID = 7,
                            Qty = 3,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 7,
                            Discount = 0m,
                            OrderID = 10249,
                            ProductID = 8,
                            Qty = 2,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 8,
                            Discount = 0m,
                            OrderID = 10249,
                            ProductID = 5,
                            Qty = 4,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 9,
                            Discount = 0m,
                            OrderID = 10248,
                            ProductID = 6,
                            Qty = 4,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 10,
                            Discount = 0m,
                            OrderID = 10248,
                            ProductID = 8,
                            Qty = 1,
                            Total = 0m,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 11,
                            Discount = 0m,
                            OrderID = 10249,
                            ProductID = 9,
                            Qty = 4,
                            Total = 0m,
                            UnitPrice = 0m
                        });
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 15.21m,
                            Created = new DateTime(2022, 2, 3, 10, 12, 50, 774, DateTimeKind.Unspecified).AddTicks(9821),
                            Deleted = false,
                            Description = "Assumenda est ut impedit voluptatem et eveniet amet est magnam dolor cupiditate vel reiciendis eos delectus excepturi et.",
                            Name = "Non earum aut officia illo."
                        },
                        new
                        {
                            Id = 2,
                            Cost = 48.63m,
                            Created = new DateTime(2022, 2, 1, 15, 53, 58, 783, DateTimeKind.Unspecified).AddTicks(7870),
                            Deleted = false,
                            Description = "Quis magnam omnis sunt excepturi suscipit et ut laborum quae quis facilis qui natus et tempora vel voluptatem nisi sint a doloribus omnis natus.",
                            Name = "Recusandae soluta cumque ut eum."
                        },
                        new
                        {
                            Id = 3,
                            Cost = 54.10m,
                            Created = new DateTime(2022, 3, 22, 9, 45, 15, 771, DateTimeKind.Unspecified).AddTicks(835),
                            Deleted = false,
                            Description = "Quia vel a facilis molestiae sint id dignissimos explicabo voluptas consequatur illum cum accusamus eius dolores veniam impedit ullam cum alias accusamus molestiae exercitationem.",
                            Name = "Non ut sunt sunt doloribus."
                        },
                        new
                        {
                            Id = 4,
                            Cost = 71.89m,
                            Created = new DateTime(2022, 12, 14, 4, 44, 9, 474, DateTimeKind.Unspecified).AddTicks(163),
                            Deleted = false,
                            Description = "Inventore quis voluptatem quia animi sequi et eos veniam ut quam sed fuga rerum rerum natus eos doloremque.",
                            Name = "Distinctio et consequatur praesentium delectus."
                        },
                        new
                        {
                            Id = 5,
                            Cost = 70.33m,
                            Created = new DateTime(2022, 8, 7, 11, 46, 29, 63, DateTimeKind.Unspecified).AddTicks(6820),
                            Deleted = false,
                            Description = "Sequi tempora at nemo quidem quidem officiis nulla possimus nemo unde perferendis eveniet magni voluptates iusto qui aut qui consequatur.",
                            Name = "Temporibus enim repudiandae qui qui."
                        },
                        new
                        {
                            Id = 6,
                            Cost = 80.73m,
                            Created = new DateTime(2022, 4, 8, 12, 49, 36, 993, DateTimeKind.Unspecified).AddTicks(4497),
                            Deleted = false,
                            Description = "Minus placeat blanditiis et facere itaque alias sunt consequatur reiciendis voluptatem.",
                            Name = "Ipsam aut sunt omnis assumenda."
                        },
                        new
                        {
                            Id = 7,
                            Cost = 87.19m,
                            Created = new DateTime(2022, 12, 14, 8, 51, 12, 171, DateTimeKind.Unspecified).AddTicks(1739),
                            Deleted = false,
                            Description = "Natus tenetur aliquid repudiandae consequatur alias facilis asperiores laborum voluptates facere minus.",
                            Name = "Dolor consectetur in perferendis nulla."
                        },
                        new
                        {
                            Id = 8,
                            Cost = 29.07m,
                            Created = new DateTime(2022, 3, 1, 14, 15, 9, 103, DateTimeKind.Unspecified).AddTicks(524),
                            Deleted = false,
                            Description = "A consequuntur suscipit et quam quo nam error necessitatibus ex id dicta qui facilis.",
                            Name = "Est aut aut pariatur soluta."
                        },
                        new
                        {
                            Id = 9,
                            Cost = 29.30m,
                            Created = new DateTime(2022, 9, 20, 4, 52, 59, 476, DateTimeKind.Unspecified).AddTicks(4928),
                            Deleted = false,
                            Description = "Reprehenderit distinctio aliquam dolore voluptate et rem libero dolor qui suscipit qui dolor et et et dolores ut laboriosam beatae aut aliquam quia libero alias.",
                            Name = "Vel fugiat facilis et aut."
                        },
                        new
                        {
                            Id = 10,
                            Cost = 23.04m,
                            Created = new DateTime(2022, 7, 6, 23, 20, 44, 90, DateTimeKind.Unspecified).AddTicks(7095),
                            Deleted = false,
                            Description = "Aut id cum dolor ipsum et quod explicabo eius quia aut placeat.",
                            Name = "Fuga qui dolor sed illum."
                        });
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Shipper", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Shipper");
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 370, DateTimeKind.Local).AddTicks(8311),
                            Deleted = false,
                            Description = "S",
                            ProductId = 1,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9057),
                            Deleted = false,
                            Description = "M",
                            ProductId = 1,
                            Qty = 100
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9103),
                            Deleted = false,
                            Description = "L",
                            ProductId = 1,
                            Qty = 100
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9108),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 1,
                            Qty = 100
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9499),
                            Deleted = false,
                            Description = "S",
                            ProductId = 2,
                            Qty = 100
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9506),
                            Deleted = false,
                            Description = "M",
                            ProductId = 2,
                            Qty = 100
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9509),
                            Deleted = false,
                            Description = "L",
                            ProductId = 2,
                            Qty = 100
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9511),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 2,
                            Qty = 100
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9519),
                            Deleted = false,
                            Description = "S",
                            ProductId = 3,
                            Qty = 100
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9522),
                            Deleted = false,
                            Description = "M",
                            ProductId = 3,
                            Qty = 100
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9525),
                            Deleted = false,
                            Description = "L",
                            ProductId = 3,
                            Qty = 100
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9527),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 3,
                            Qty = 100
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9534),
                            Deleted = false,
                            Description = "S",
                            ProductId = 4,
                            Qty = 100
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9536),
                            Deleted = false,
                            Description = "M",
                            ProductId = 4,
                            Qty = 100
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9539),
                            Deleted = false,
                            Description = "L",
                            ProductId = 4,
                            Qty = 100
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9541),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 4,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9546),
                            Deleted = false,
                            Description = "S",
                            ProductId = 5,
                            Qty = 100
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9549),
                            Deleted = false,
                            Description = "M",
                            ProductId = 5,
                            Qty = 100
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9552),
                            Deleted = false,
                            Description = "L",
                            ProductId = 5,
                            Qty = 100
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9555),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 5,
                            Qty = 100
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9560),
                            Deleted = false,
                            Description = "S",
                            ProductId = 6,
                            Qty = 100
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9563),
                            Deleted = false,
                            Description = "M",
                            ProductId = 6,
                            Qty = 100
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9565),
                            Deleted = false,
                            Description = "L",
                            ProductId = 6,
                            Qty = 100
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9568),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 6,
                            Qty = 100
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9573),
                            Deleted = false,
                            Description = "S",
                            ProductId = 7,
                            Qty = 100
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9576),
                            Deleted = false,
                            Description = "M",
                            ProductId = 7,
                            Qty = 100
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9578),
                            Deleted = false,
                            Description = "L",
                            ProductId = 7,
                            Qty = 100
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9580),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 7,
                            Qty = 100
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9585),
                            Deleted = false,
                            Description = "S",
                            ProductId = 8,
                            Qty = 100
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9588),
                            Deleted = false,
                            Description = "M",
                            ProductId = 8,
                            Qty = 100
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9591),
                            Deleted = false,
                            Description = "L",
                            ProductId = 8,
                            Qty = 100
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9593),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 8,
                            Qty = 100
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9598),
                            Deleted = false,
                            Description = "S",
                            ProductId = 9,
                            Qty = 100
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9601),
                            Deleted = false,
                            Description = "M",
                            ProductId = 9,
                            Qty = 100
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9603),
                            Deleted = false,
                            Description = "L",
                            ProductId = 9,
                            Qty = 100
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9606),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 9,
                            Qty = 100
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9611),
                            Deleted = false,
                            Description = "S",
                            ProductId = 10,
                            Qty = 100
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9614),
                            Deleted = false,
                            Description = "M",
                            ProductId = 10,
                            Qty = 100
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9617),
                            Deleted = false,
                            Description = "L",
                            ProductId = 10,
                            Qty = 100
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTime(2023, 2, 9, 15, 40, 16, 372, DateTimeKind.Local).AddTicks(9619),
                            Deleted = false,
                            Description = "XL",
                            ProductId = 10,
                            Qty = 100
                        });
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Order", b =>
                {
                    b.HasOne("MarketPlaceCrm.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPlaceCrm.Data.Entities.Shipper", "Shipper")
                        .WithMany()
                        .HasForeignKey("ShipperID");
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("MarketPlaceCrm.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPlaceCrm.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("MarketPlaceCrm.Data.Entities.Stock", b =>
                {
                    b.HasOne("MarketPlaceCrm.Data.Entities.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
